"""upgrade migration pp

Revision ID: 8077202e8531
Revises: d7db2534d5ee
Create Date: 2019-05-29 14:45:00.520281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8077202e8531'
down_revision = 'd7db2534d5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
